#!/bin/sh
# agi-out-states.t.sh [TRUNK] [GITDIR]: the out-line's crash windows and refusals, run against the agi-out PIECE alone in a scratch HOME (AGI_OUT=<file> tests a candidate; else `sect agi-out` of TRUNK). SM mur sm17 on 00ffbe04c: R3 a crash between the two key-file moves, R4 a crash after the seal moved before the scratch dir went (a 2nd commit for ONE .fresh), R5 no capsule / no seal key must REFUSE, never replace the seal. sh + git + ssh-keygen + python3 cryptography, no network, nothing pushed. One ok/FAIL line per case; exit = FAIL count.
T=${1:-local-maxxing/season2/main};G=${2:-$(git rev-parse --path-format=absolute --git-common-dir)};D=$(mktemp -d);trap 'rm -rf $D' EXIT;f=0;GEO=.agi/nodes/.geometry
o=$(git rev-parse $T)||exit 1;git ls-tree --full-tree --name-only $o $GEO/|grep '/engine[^/]*\.md$'|sed "s|^|$o:|"|git cat-file --batch --follow-symlinks|sed -n "/^###* agi-out /,/^###* /{/^~~~/,/^~~~/{//!p}}">$D/agi-out;[ "$AGI_OUT" ]&&cp $AGI_OUT $D/agi-out;[ -s $D/agi-out ]||{ echo "FAIL no agi-out piece at $T";exit 99;}
ok(){ if eval "$2";then echo "ok $1";else echo "FAIL $1";f=$((f+1));fi;}
unset GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL GIT_DIR GIT_WORK_TREE AGI_CAPSULE
mkh(){ H=$D/h$1;rm -rf $H;mkdir -p $H/.ssh;ssh-keygen -qN "" -ted25519 -f$H/.ssh/id_ed25519>/dev/null
 python3 -c "import base64 as B;from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey as K;k=K.generate();open('$H/seal.key','w').write(B.b64encode(k.private_bytes_raw()).decode());print(B.b64encode(k.public_key().public_bytes_raw()).decode())">$H/seal.pub
 printf '[gpg]\nformat=ssh\n[commit]\ngpgsign=true\n[user]\nsigningkey=%s/.ssh/id_ed25519.pub\n[safe]\n\tdirectory=*\n' $H>$H/.gitconfig
 git init -q $H/t;mkdir -p $H/t/$GEO;printf 'post1 ssh-ed25519 %s\npost1 pq-sha256 %s\npost1 x25519 %s\n' "$(awk '{print $2}' $H/.ssh/id_ed25519.pub)" "$(head -c32 /dev/urandom|base64)" "$(cat $H/seal.pub)">$H/t/$GEO/ring;(cd $H/t;GIT_CONFIG_GLOBAL=/dev/null git -c user.name=x -c user.email=x@x -c commit.gpgsign=false add -A;GIT_CONFIG_GLOBAL=/dev/null git -c user.name=x -c user.email=x@x -c commit.gpgsign=false commit -qm ring0)
 sleep 1;touch $H/.fresh;mkdir -p $D/cap$1;python3 -c "import sys,base64 as B,hashlib as H;from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey as K,X25519PublicKey as P;from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305 as C;e=K.generate();h=lambda x:H.sha256(x).digest();q=P.from_public_bytes(B.b64decode(open('$H/seal.pub').read().strip()));print('post1',B.b64encode(e.public_key().public_bytes_raw()+C(h(e.exchange(q))).encrypt(bytes(12),b'1:123456789',None)).decode())">$D/cap$1/post1;}
out(){ (cd $H;env -u GIT_DIR HOME=$H GIT_CONFIG_GLOBAL=$H/.gitconfig GIT_AUTHOR_NAME=post1 GIT_COMMITTER_NAME=post1 GIT_AUTHOR_EMAIL=post1@agi GIT_COMMITTER_EMAIL=post1@agi AGI_SEAT=post1 ${CAP:+AGI_CAPSULE=$CAP} sh $D/agi-out)>$D/o 2>&1;}
nc(){ git -C $H/t rev-list --count HEAD;}
# --- R4: a crash after the seal moved, before the scratch dir went: the resume leaves ONE ring commit for the one .fresh
mkh 1;CAP=$D/cap1;out;c1=$(nc);ok "base-one-commit one out-line is ONE ring commit on top of the genesis (2 commits in all, got $c1)" '[ $c1 = 2 ]'
mkdir -p $H/.ssh/n;git -C $H/t show HEAD:$GEO/ring|awk '$2=="x25519"{print $3}'>$H/.ssh/n/seal.pub;sleep 1;touch $H/.fresh;out;ok "r4-resume-after-seal-moved the .ssh/n left behind after the seal moved (only seal.pub in it) is cleaned up and adds NO second commit (commits $(nc), want 2)" '[ "$(nc)" = 2 ]&&[ ! -d $H/.ssh/n ]'
# --- R3: a crash between the two key-file moves (the private key moved, the public one still in .ssh/n): the resume installs the .pub too
mkh 2;CAP=$D/cap2;out;git -C $H/t show HEAD:$GEO/ring|awk '$2=="x25519"{print $3}'>$D/xs2;mkdir -p $H/.ssh/n;cp $D/xs2 $H/.ssh/n/seal.pub;cp $H/.ssh/id_ed25519.pub $H/.ssh/n/id_ed25519.pub;ssh-keygen -qN "" -ted25519 -f$D/old2>/dev/null;cp $D/old2.pub $H/.ssh/id_ed25519.pub
sleep 1;touch $H/.fresh;touch $H/.ssh/id_ed25519;sleep 1;touch $H/.fresh;out;ok "r3-pub-installed-on-resume after a crash between the key moves the resume installs the public key too: .ssh/id_ed25519.pub equals the ring's ssh-ed25519 column (commits $(nc))" '[ "$(awk "{print \$2}" $H/.ssh/id_ed25519.pub)" = "$(git -C $H/t show HEAD:$GEO/ring|awk "\$2==\"ssh-ed25519\"{print \$3}")" ]'
# --- R5: a seal key exists but no capsule is set: REFUSE, replace nothing, commit nothing
mkh 3;s0=$(cat $H/seal.key);k0=$(cat $H/.ssh/id_ed25519.pub);CAP= out;rc=$?;ok "r5-no-capsule-refused a seal key with no AGI_CAPSULE: the out-line refuses (no new commit: $(nc), seal key and sign key unchanged)" '[ "$(nc)" = 1 ]&&[ "$(cat $H/seal.key)" = "$s0" ]&&[ "$(cat $H/.ssh/id_ed25519.pub)" = "$k0" ]&&[ ! -d $H/.ssh/n ]'
mkh 4;rm -f $H/seal.key;CAP=$D/cap4;out;ok "r5-share-without-seal-refused a capsule share exists but ~/seal.key is gone: refuse, no commit (commits $(nc))" '[ "$(nc)" = 1 ]'
# --- R1 (SM mur sm19 on OUT.2): NO ring bytes reach the worktree before the wrap has succeeded (agi-flush -> agi-turn runs `git add -A;git commit` in ~/t after a failed start)
turn(){ git -C $H/t add -A;GIT_CONFIG_GLOBAL=/dev/null git -C $H/t -c user.name=x -c user.email=x@x -c commit.gpgsign=false commit -qm turn>/dev/null 2>&1;}
dec(){ python3 -c "import base64 as B,hashlib as H;from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey as K,X25519PublicKey as P;from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305 as C;h=lambda x:H.sha256(x).digest();p,z=open('$D/cap$1/post1').read().split();z=B.b64decode(z);print(C(h(K.from_private_bytes(B.b64decode(open('$H/seal.key').read())).exchange(P.from_public_bytes(z[:32])))).decrypt(bytes(12),z[32:],None).decode())" 2>/dev/null;}
mkh 5;echo 'post1 AAAAAAAA'>$D/cap5/post1;CAP=$D/cap5;out;rc=$?;turn
ok "r1a-undecryptable-share-leaves-no-ring a share that cannot be unwrapped: the start fails (rc=$rc), the ring is NOT dirty ($(git -C $H/t status --porcelain -- $GEO/ring|wc -l) lines), agi-turn's sweep adds NO commit (now $(nc), want 1), no .ssh/n left" '[ $rc != 0 ]&&[ -z "$(git -C $H/t status --porcelain -- $GEO/ring)" ]&&[ "$(nc)" = 1 ]&&[ ! -d $H/.ssh/n ]'
mkh 6;mkdir -p $D/shim6;printf '#!/bin/sh\ncase " $* " in *" wrap "*)kill -9 $PPID;;esac\nexec /usr/bin/python3 "$@"\n'>$D/shim6/python3;chmod +x $D/shim6/python3;PS0=$PATH;PATH=$D/shim6:$PATH;CAP=$D/cap6;out;rc=$?;PATH=$PS0;turn
ok "r1b-kill-mid-wrap-leaves-no-ring the agi-out process KILLED inside the python wrap (rc=$rc): the ring is not dirty and agi-turn adds NO commit (now $(nc), want 1)" '[ $rc != 0 ]&&[ -z "$(git -C $H/t status --porcelain -- $GEO/ring)" ]&&[ "$(nc)" = 1 ]'
touch $H/.fresh;CAP=$D/cap6;out;rc2=$?;ok "r1c-restart-after-kill-rewraps the next start (python healthy) re-wraps and lands ONE out-line (rc=$rc2, commits $(nc), want 2), the share opens with the NEW seal key ($(dec 6)), the ring's x25519 column is that seal's public key" '[ $rc2 = 0 ]&&[ "$(nc)" = 2 ]&&[ "$(dec 6)" = 1:123456789 ]&&[ ! -d $H/.ssh/n ]&&[ "$(git -C $H/t show HEAD:$GEO/ring|awk '$2=="x25519"{print $3}')" = "$(python3 -c "import base64 as B;from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey as K;print(B.b64encode(K.from_private_bytes(B.b64decode(open('$H/seal.key').read())).public_key().public_bytes_raw()).decode())")" ]'
# --- D1: the new key must reach the root allowed_signers in the SAME start: an agi-signers line runs AFTER agi-out in the post unit
git show $o:$GEO/engine-root.md>$D/er;U=$(sed -n '/^### agi-post@.service/,/^~~~$/p' $D/er);ln_out=$(echo "$U"|grep -n "ExecStartPre=sh -c 'agi-out'"|cut -d: -f1);ln_sig=$(echo "$U"|grep -n 'agi-signers %i'|tail -1|cut -d: -f1)
ok "d1-signers-after-out the post unit runs agi-signers AFTER agi-out (agi-out at line ${ln_out:-none}, the last agi-signers at ${ln_sig:-none})" '[ -n "$ln_out" ]&&[ -n "$ln_sig" ]&&[ "$ln_sig" -gt "$ln_out" ]'
echo "agi-out-states: $f FAIL";exit $f
