#!/bin/sh
# agi-out-states.t.sh [TRUNK] [GITDIR]: the out-line's crash windows and refusals, run against the agi-out PIECE alone in a scratch HOME (AGI_OUT=<file> tests a candidate; else `sect agi-out` of TRUNK). SM mur sm17 on 00ffbe04c: R3 a crash between the two key-file moves, R4 a crash after the seal moved before the scratch dir went (a 2nd commit for ONE .fresh), R5 no capsule / no seal key must REFUSE, never replace the seal. sh + git + ssh-keygen + python3 cryptography, no network, nothing pushed. One ok/FAIL line per case; exit = FAIL count.
T=${1:-local-maxxing/season2/main};G=${2:-$(git rev-parse --path-format=absolute --git-common-dir)};D=$(mktemp -d);trap 'rm -rf $D' EXIT;f=0;GEO=.agi/nodes/.geometry
o=$(git rev-parse $T)||exit 1;git ls-tree --full-tree --name-only $o $GEO/|grep '/engine[^/]*\.md$'|sed "s|^|$o:|"|git cat-file --batch --follow-symlinks>$D/eng;mkdir $D/bin;sed -n "/^###* agi-out /,/^###* /{/^~~~/,/^~~~/{//!p}}" $D/eng>$D/agi-out;sed -n "/^###* agi-at /,/^###* /{/^~~~/,/^~~~/{//!p}}" $D/eng>$D/bin/agi-at;[ "$AGI_OUT" ]&&cp $AGI_OUT $D/agi-out;[ "$AGI_AT" ]&&cp $AGI_AT $D/bin/agi-at;chmod +x $D/bin/agi-at 2>/dev/null;[ -s $D/agi-out ]||{ echo "FAIL no agi-out piece at $T";exit 99;};[ -s $D/bin/agi-at ]||{ echo "FAIL no agi-at piece at $T (agi-out's ring commit is agi-at on the ring path)";exit 99;}
ok(){ if eval "$2";then echo "ok $1";else echo "FAIL $1";f=$((f+1));fi;}
unset GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL GIT_DIR GIT_WORK_TREE AGI_CAPSULE
mkh(){ H=$D/h$1;rm -rf $H;mkdir -p $H/.ssh;ssh-keygen -qN "" -ted25519 -f$H/.ssh/id_ed25519>/dev/null
 python3 -c "import base64 as B;from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey as K;k=K.generate();open('$H/seal.key','w').write(B.b64encode(k.private_bytes_raw()).decode());print(B.b64encode(k.public_key().public_bytes_raw()).decode())">$H/seal.pub
 printf '[gpg]\nformat=ssh\n[commit]\ngpgsign=true\n[user]\nsigningkey=%s/.ssh/id_ed25519.pub\n[safe]\n\tdirectory=*\n' $H>$H/.gitconfig
 git init -q -b trunk $H/t;mkdir -p $H/t/$GEO;printf 'post1 ssh-ed25519 %s\npost1 pq-sha256 %s\npost1 x25519 %s\n' "$(awk '{print $2}' $H/.ssh/id_ed25519.pub)" "$(head -c32 /dev/urandom|base64)" "$(cat $H/seal.pub)">$H/t/$GEO/ring;(cd $H/t;GIT_CONFIG_GLOBAL=/dev/null git -c user.name=x -c user.email=x@x -c commit.gpgsign=false add -A;GIT_CONFIG_GLOBAL=/dev/null git -c user.name=x -c user.email=x@x -c commit.gpgsign=false commit -qm ring0;git branch posts/post1;git checkout -q --detach posts/post1)
 sleep 1;touch $H/.fresh;mkdir -p $H/capsule;python3 -c "import sys,base64 as B,hashlib as H;from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey as K,X25519PublicKey as P;from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305 as C;e=K.generate();h=lambda x:H.sha256(x).digest();q=P.from_public_bytes(B.b64decode(open('$H/seal.pub').read().strip()));print('post1',B.b64encode(e.public_key().public_bytes_raw()+C(h(e.exchange(q))).encrypt(bytes(12),b'1:123456789',None)).decode())">$H/capsule/post1;}
out(){ (cd $H;env -u GIT_DIR HOME=$H GIT_CONFIG_GLOBAL=$H/.gitconfig GIT_CONFIG_SYSTEM=/dev/null GIT_TEST_ASSUME_DIFFERENT_OWNER=1 GIT_AUTHOR_NAME=post1 GIT_COMMITTER_NAME=post1 GIT_AUTHOR_EMAIL=post1@agi GIT_COMMITTER_EMAIL=post1@agi AGI_SEAT=post1 AGI_POST=post1 PATH=$D/bin:$PATH ${CAP:+"AGI_CAPSULE=$CAP"} sh $D/agi-out)>$D/o 2>&1;rc=$?;return $rc;}
nc(){ git -C $H/t rev-list --count refs/heads/posts/post1;}
# --- R4: a crash after the seal moved, before the scratch dir went: the resume leaves ONE ring commit for the one .fresh
mkh 1;CAP=capsule;out;c1=$(nc);ok "base-one-commit one out-line is ONE ring commit on top of the genesis (2 commits in all, got $c1)" '[ $c1 = 2 ]'
mkdir -p $H/.ssh/n;git -C $H/t show HEAD:$GEO/ring|awk '$2=="x25519"{print $3}'>$H/.ssh/n/seal.pub;sleep 1;touch $H/.fresh;out;ok "r4-resume-after-seal-moved the .ssh/n left behind after the seal moved (only seal.pub in it) is cleaned up and adds NO second commit (commits $(nc), want 2)" '[ "$(nc)" = 2 ]&&[ ! -d $H/.ssh/n ]'
# --- R3: a crash between the two key-file moves (the private key moved, the public one still in .ssh/n): the resume installs the .pub too
mkh 2;CAP=capsule;out;git -C $H/t show HEAD:$GEO/ring|awk '$2=="x25519"{print $3}'>$D/xs2;mkdir -p $H/.ssh/n;cp $D/xs2 $H/.ssh/n/seal.pub;cp $H/.ssh/id_ed25519.pub $H/.ssh/n/id_ed25519.pub;ssh-keygen -qN "" -ted25519 -f$D/old2>/dev/null;cp $D/old2.pub $H/.ssh/id_ed25519.pub
sleep 1;touch $H/.fresh;touch $H/.ssh/id_ed25519;sleep 1;touch $H/.fresh;out;ok "r3-pub-installed-on-resume after a crash between the key moves the resume installs the public key too: .ssh/id_ed25519.pub equals the ring's ssh-ed25519 column (commits $(nc))" '[ "$(awk "{print \$2}" $H/.ssh/id_ed25519.pub)" = "$(git -C $H/t show HEAD:$GEO/ring|awk "\$2==\"ssh-ed25519\"{print \$3}")" ]'
# --- R5: a seal key exists but no capsule is set: REFUSE, replace nothing, commit nothing
mkh 3;s0=$(cat $H/seal.key);k0=$(cat $H/.ssh/id_ed25519.pub);CAP= out;rc=$?;ok "r5-no-capsule-refused a seal key with no AGI_CAPSULE: the out-line refuses (no new commit: $(nc), seal key and sign key unchanged)" '[ "$(nc)" = 1 ]&&[ "$(cat $H/seal.key)" = "$s0" ]&&[ "$(cat $H/.ssh/id_ed25519.pub)" = "$k0" ]&&[ ! -d $H/.ssh/n ]'
mkh 4;rm -f $H/seal.key;CAP=capsule;out;ok "r5-share-without-seal-refused a capsule share exists but ~/seal.key is gone: refuse, no commit (commits $(nc))" '[ "$(nc)" = 1 ]'
# --- R1 (SM mur sm19 on OUT.2): NO ring bytes reach the worktree before the wrap has succeeded (agi-flush -> agi-turn runs `git add -A;git commit` in ~/t after a failed start)
# turn: the WORST-CASE sweep after a failed start = ONE agi-at of everything dirty in t ("." : what the old agi-turn did with `git add -A;git commit`; the v5 agi-turn commits only a node tree and reports a stray t edit as [out-of-tree], so this models the sweep that would hurt, and the row stays non-vacuous: a dirty ring in t makes it land a commit ON posts/post1, which nc counts)
turn(){ (cd $H;env -u GIT_DIR HOME=$H GIT_CONFIG_GLOBAL=$H/.gitconfig GIT_CONFIG_SYSTEM=/dev/null GIT_TEST_ASSUME_DIFFERENT_OWNER=1 GIT_AUTHOR_NAME=post1 GIT_COMMITTER_NAME=post1 GIT_AUTHOR_EMAIL=post1@agi GIT_COMMITTER_EMAIL=post1@agi AGI_POST=post1 PATH=$D/bin:$PATH agi-at .)>/dev/null 2>&1;}
dec(){ python3 -c "import base64 as B,hashlib as H;from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey as K,X25519PublicKey as P;from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305 as C;h=lambda x:H.sha256(x).digest();p,z=open('$H/capsule/post1').read().split();z=B.b64decode(z);print(C(h(K.from_private_bytes(B.b64decode(open('$H/seal.key').read())).exchange(P.from_public_bytes(z[:32])))).decrypt(bytes(12),z[32:],None).decode())" 2>/dev/null;}
ringx(){ git -C $H/t show HEAD:$GEO/ring|awk '$2=="x25519"{print $3}';}
pubx(){ python3 -c "import base64 as B;from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey as K;print(B.b64encode(K.from_private_bytes(B.b64decode(open('$H/seal.key').read())).public_key().public_bytes_raw()).decode())" 2>/dev/null;}
mkh 5;echo 'post1 AAAAAAAA'>$H/capsule/post1;CAP=capsule;out;rc=$?;turn
ok "r1a-undecryptable-share-leaves-no-ring a share that cannot be unwrapped: the start fails (rc=$rc), the ring is NOT dirty ($(git -C $H/t status --porcelain -- $GEO/ring|wc -l) lines), agi-turn's sweep adds NO commit (now $(nc), want 1), no .ssh/n left" '[ $rc != 0 ]&&[ -z "$(git -C $H/t status --porcelain -- $GEO/ring)" ]&&[ "$(nc)" = 1 ]&&[ ! -d $H/.ssh/n ]'
mkh 6;mkdir -p $D/shim6;printf '#!/bin/sh\ncase " $* " in *" wrap "*)kill -9 $PPID;;esac\nexec /usr/bin/python3 "$@"\n'>$D/shim6/python3;chmod +x $D/shim6/python3;PS0=$PATH;PATH=$D/shim6:$PATH;CAP=capsule;out;rc=$?;PATH=$PS0;turn
ok "r1b-kill-mid-wrap-leaves-no-ring the agi-out process KILLED inside the python wrap (rc=$rc): the ring is not dirty and agi-turn adds NO commit (now $(nc), want 1)" '[ $rc != 0 ]&&[ -z "$(git -C $H/t status --porcelain -- $GEO/ring)" ]&&[ "$(nc)" = 1 ]'
touch $H/.fresh;CAP=capsule;out;rc2=$?;ok "r1c-restart-after-kill-rewraps the next start (python healthy) re-wraps and lands ONE out-line (rc=$rc2, commits $(nc), want 2), the share opens with the NEW seal key ($(dec 6)), the ring's x25519 column is that seal's public key" '[ $rc2 = 0 ]&&[ "$(nc)" = 2 ]&&[ "$(dec 6)" = 1:123456789 ]&&[ ! -d $H/.ssh/n ]&&[ "$(ringx)" = "$(pubx)" ]'
# --- D1: the new key must reach the root allowed_signers in the SAME start: an agi-signers line runs AFTER agi-out in the post unit
git show $o:$GEO/engine-root.md>$D/er;U=$(sed -n '/^### agi-post@.service/,/^~~~$/p' $D/er);ln_out=$(echo "$U"|grep -n "^ExecStartPre=sh -c '.*exec agi-out"|cut -d: -f1);ln_sig=$(echo "$U"|grep -n 'agi-signers %i'|tail -1|cut -d: -f1)
ok "d1-signers-after-out the post unit runs agi-signers AFTER agi-out (agi-out at line ${ln_out:-none}, the last agi-signers at ${ln_sig:-none})" '[ -n "$ln_out" ]&&[ -n "$ln_sig" ]&&[ "$ln_sig" -gt "$ln_out" ]'
# --- OUT.4 (belam 09:18Z rule via SM; DG1 09:1xZ order): the capsule DIR is relative to HOME and refused otherwise; a refused out-line STOPS loud and ONCE (exit 75, marker ~/.ssh/out-refused, the unit's ExecCondition skips later starts)
chk(){ [ "$rc" = 75 ]&&[ "$(nc)" = 1 ]&&[ -s $H/.ssh/out-refused ]&&[ ! -d $H/.ssh/n ]&&[ -z "$(git -C $H/t status --porcelain)" ]&&[ "$(grep -c '^agi-out:' $D/o)" = 1 ];}
mkh 7;CAP=$D/abs7;out;ok "p1-absolute-refused an ABSOLUTE AGI_CAPSULE: exit 75, no ring commit, no .ssh/n, ONE agi-out: line, the reason in ~/.ssh/out-refused (commits $(nc))" 'chk'
cp $H/.ssh/out-refused $D/m7;out;rc=$?;ok "m1-second-start-silent the same start again (no newer .fresh): exit 75, NO output, the marker unchanged (rc=$rc, $(wc -c <$D/o) B printed)" '[ "$rc" = 75 ]&&[ ! -s $D/o ]&&cmp -s $H/.ssh/out-refused $D/m7'
sleep 1;touch $H/.fresh;CAP=capsule out;rc=$?;ok "m2-newer-fresh-retries a .fresh newer than the marker: the retry with a valid value lands ONE ring commit (commits $(nc), want 2, rc=$rc) and the marker is gone" '[ "$rc" = 0 ]&&[ "$(nc)" = 2 ]&&[ ! -e $H/.ssh/out-refused ]'
mkh 8;CAP=../x out;ok "p2-dotdot-refused an AGI_CAPSULE with .. : exit 75, no ring commit (commits $(nc))" 'chk'
mkh 9;mkdir -p $H/t/cap;CAP=t/cap out;ok "p3-inside-t-refused an AGI_CAPSULE inside the worktree t (the Stop hook's git add -A would commit it): refused (commits $(nc))" 'chk'
mkh 10;CAP=./t out;ok "p4-dot-t-refused ./t resolves to t: refused" 'chk'
mkh 11;ln -s t $H/lnk;CAP=lnk out;ok "p5-symlink-into-t-refused a relative value that is a SYMLINK into t resolves inside t: refused" 'chk'
mkh 12;CAP=capsule out;rc=$?;ok "p6-valid-lands-modes a valid relative value (capsule): lands (rc=$rc, commits $(nc)), the share is 0600 ($(stat -c %a $H/capsule/post1); a dir that already exists keeps its mode: named), no marker" '[ "$rc" = 0 ]&&[ "$(nc)" = 2 ]&&[ "$(stat -c %a $H/capsule/post1)" = 600 ]&&[ ! -e $H/.ssh/out-refused ]'
mkh 13;rm -rf $H/capsule;CAP=capsule out;rc=$?;ok "p7-dir-created-0700 the capsule dir absent: agi-out creates it 0700 as the post (rc=$rc, mode $(stat -c %a $H/capsule 2>/dev/null))" '[ "$rc" = 0 ]&&[ "$(stat -c %a $H/capsule)" = 700 ]'
# --- OUT.5 (SM mur sm19 on OUT.4, R1-R3): the rail resolves with readlink -m (a deep missing tail through a symlink into t resolves INTO t), requires the result under HOME and not t, and takes only [A-Za-z0-9._/-] without a leading -
mkh 14;ln -s t $H/lnk;CAP=lnk/a/b out;ok "q1-deep-missing-through-symlink-into-t-refused ~/lnk -> t with AGI_CAPSULE=lnk/a/b (two missing components, readlink -f prints nothing): refused, nothing created inside t (commits $(nc))" 'chk&&[ ! -e $H/t/a ]'
mkh 15;rm -rf $H/capsule;ln -s t $H/capsule;CAP=capsule/x/y out;ok "q2-capsule-symlink-into-t-deep-refused ~/capsule -> t with capsule/x/y: refused, nothing created inside t" 'chk&&[ ! -e $H/t/x ]'
mkh 16;rm -rf $H/capsule;mkdir $D/outside16;ln -s $D/outside16 $H/capsule;CAP=capsule out;ok "q3-symlink-leaving-home-refused ~/capsule -> a directory outside HOME: refused (relative to HOME means under HOME), nothing written there" 'chk&&[ -z "$(ls $D/outside16)" ]'
mkh 17;CAP='cap*' out;ok "q4-glob-refused a glob value (cap*) is refused: a rotation with rc 0 and NO re-wrap would lose the share" 'chk'
mkh 18;CAP=-m777 out;ok "q5-option-shaped-refused an option-shaped value (-m777) is refused (it would reach mkdir / rm as a flag)" 'chk'
mkh 19;CAP='a b' out;ok "q6-space-refused a value with a space is refused" 'chk'
mkh 20;CAP='a:b' out;ok "q7-colon-refused a value with a colon is refused" 'chk'
mkh 21;CAP=capsule/deep/er out;rc=$?;ok "q8-deep-missing-under-home-ok a valid DEEP relative value whose tail does not exist yet is created under HOME and lands (rc=$rc, commits $(nc), dir $(stat -c %a $H/capsule/deep/er 2>/dev/null))" '[ "$rc" = 0 ]&&[ "$(nc)" = 2 ]&&[ -d $H/capsule/deep/er ]'
# --- OUT.6 (SM mur sm20 on OUT.5, D1/D2; DG1 steer): a keygen / seal-gen refusal removes the ~/.ssh/n THIS run created (a private sign key) but never the RESUME state a refusal finds; the rail is POSITIVE: the resolved path must be ~/capsule or below
mkdir -p $D/shimK $D/shimG;printf '#!/bin/sh\nexit 1\n'>$D/shimK/ssh-keygen;printf '#!/bin/sh\ncase " $* " in *" gen "*)exit 1;;esac\nexec /usr/bin/python3 "$@"\n'>$D/shimG/python3;chmod +x $D/shimK/ssh-keygen $D/shimG/python3
mkh 22;PS0=$PATH;PATH=$D/shimK:$PATH;CAP=capsule out;PATH=$PS0;ok "s1-keygen-failure-leaves-no-n ssh-keygen failing: refused (75, marker, ONE line), no ~/.ssh/n, no commit (commits $(nc))" 'chk'
mkh 23;PS0=$PATH;PATH=$D/shimG:$PATH;CAP=capsule out;PATH=$PS0;ok "s2-sealgen-failure-leaves-no-n the seal key generation failing AFTER the new sign key was made: refused, NO ~/.ssh/n left (it held a NEW private sign key), no commit (commits $(nc))" 'chk&&[ ! -e $H/.ssh/n ]'
mkh 24;CAP=capsule out;git -C $H/t show HEAD:$GEO/ring|awk '$2=="x25519"{print $3}'>$D/xs24;mkdir -p $H/.ssh/n;cp $D/xs24 $H/.ssh/n/seal.pub;echo resume>$H/.ssh/n/id_ed25519;sleep 1;touch $H/.fresh;CAP=$D/abs24 out;rc=$?;ok "s3-refusal-keeps-resume-state a refusal that runs BEFORE any keygen (a bad AGI_CAPSULE) while ~/.ssh/n is the resume state of a landed ring commit keeps it (rc=$rc, .ssh/n: $(ls $H/.ssh/n 2>/dev/null|tr '\n' ' '), commits $(nc), want 2)" '[ "$rc" = 75 ]&&[ -e $H/.ssh/n/id_ed25519 ]&&[ "$(nc)" = 2 ]'
for v in .ssh/n .ssh .fresh seal.key bin hooks .claude/x o .gitconfig other; do mkh 25;s0=$(cat $H/seal.key);mkdir -p $H/other;CAP=$v out;ok "d2-reserved-$(echo $v|tr '/.' '__') AGI_CAPSULE=$v (a name under HOME that is not ~/capsule): refused (75, no ring commit, seal.key unchanged, commits $(nc))" 'chk&&[ "$(cat $H/seal.key)" = "$s0" ]&&[ -f $H/capsule/post1 ]';done
mkh 26;mkdir -p $H/other;rm -rf $H/capsule;ln -s other $H/capsule;CAP=capsule out;ok "d2-symlink-to-other-home-dir-refused ~/capsule -> ~/other (inside HOME, not ~/capsule physically): refused (BOUND: the capsule dir must be physically under ~/capsule)" 'chk'
mkh 27;CAP=capsule/sub out;rc=$?;ok "d2-capsule-sub-admitted a deeper value UNDER ~/capsule (capsule/sub) is admitted (rc=$rc, commits $(nc))" '[ "$rc" = 0 ]&&[ "$(nc)" = 2 ]'
# the unit's ExecCondition lines (DG1 02:23Z, A3 added a SECOND one, the agi-run skip): the refusal is an ExecCondition, not an ExecStartPre, because RestartPreventExitStatus has no effect on ExecStartPre. Rule: exactly ONE ExecCondition mentions out-refused, EVERY ExecCondition precedes the first ExecStartPre, each carries a skip code (exit N) that is neither 0 nor 1 (SuccessExitStatus keeps 1). cx runs the out-refused one.
git show $o:$GEO/engine-root.md|sed -n '/^### agi-post@.service/,/^~~~$/p'>$D/unit;grep '^ExecCondition=' $D/unit>$D/ecs;ec=$(grep out-refused $D/ecs|sed -n "s/^ExecCondition=sh -c '\(.*\)'\$/\1/p")
nec=$(grep -c . $D/ecs);nor=$(grep -c out-refused $D/ecs);lastec=$(grep -n '^ExecCondition=' $D/unit|tail -1|cut -d: -f1);firstpre=$(grep -n '^ExecStartPre=' $D/unit|head -1|cut -d: -f1);badcode=0
while IFS= read -r l;do cs=$(printf '%s\n' "$l"|grep -o 'exit [0-9][0-9]*'|sed 's/exit //');[ -n "$cs" ]||badcode=$((badcode+1));for c in $cs;do [ $c != 0 ]&&[ $c != 1 ]||badcode=$((badcode+1));done;done <$D/ecs
ok "c0-execcondition-first $nec ExecCondition line(s) (want >= 1), $nor mention out-refused (want exactly 1), the last ExecCondition is line $lastec and the first ExecStartPre line $firstpre (want every ExecCondition first), $badcode skip code(s) that are missing, 0 or 1 (want 0), and SuccessExitStatus keeps 1" '[ -n "$ec" ]&&[ "$nec" -ge 1 ]&&[ "$nor" = 1 ]&&[ -n "$lastec" ]&&[ -n "$firstpre" ]&&[ "$lastec" -lt "$firstpre" ]&&[ "$badcode" = 0 ]&&grep -q "^SuccessExitStatus=1 " $D/unit'
cx(){ (cd $E&&sh -c "$ec");}
E=$D/e1;mkdir -p $E/.ssh;touch $E/.fresh;cx;a=$?;sleep 1;echo x>$E/.ssh/out-refused;cx;b=$?;sleep 1;touch $E/.fresh;cx;c=$?;rm $E/.fresh;cx;d=$?
ok "c1-execcondition-states no marker: $a (0); marker newer than .fresh: $b (2); .fresh newer than the marker: $c (0); marker and no .fresh: $d (2)" '[ $a = 0 ]&&[ $b = 2 ]&&[ $c = 0 ]&&[ $d = 2 ]'
# z1 (DG1 04:44Z re-scope: the real-ownership env is the DEFAULT of every A-range lane): this lane never reads a foreign-uid repo -- the piece reads the post's OWN ~/t, and its grant is the post's ~/.gitconfig (safe.directory=*) -- so the env is on by default and ONE row proves it: under the lane's env (empty config + git's different-owner seam) a plain git read of its t is REFUSED as dubious ownership, and the grant the unit gives (safe.directory=*) lifts it
mkh 28;sn=$(cd $H/t&&env -i PATH=$PATH HOME=$H GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null GIT_TEST_ASSUME_DIFFERENT_OWNER=1 git rev-parse HEAD 2>&1|grep -c 'dubious ownership');gn=$(cd $H/t&&env -i PATH=$PATH HOME=$H GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null GIT_TEST_ASSUME_DIFFERENT_OWNER=1 git -c safe.directory='*' rev-parse HEAD >/dev/null 2>&1;echo $?)
ok "z1-real-ownership-default-is-on a plain git read of t under an empty config + GIT_TEST_ASSUME_DIFFERENT_OWNER=1: $sn dubious-ownership line(s) (want 1: the seam bites on this lane's t); with the unit's safe.directory=* grant: rc $gn (want 0)" '[ "$sn" = 1 ]&&[ "$gn" = 0 ]'
# --- RA1 (agi-at's CAS, the m5 survivor): a racer advances posts/post1 between agi-at's read and its update-ref (a git shim on commit-tree): the CAS misses, our ring commit is NOT on the branch, the racer's commit stays the tip. Only the BRANCH outcome is pinned (whether .ssh/n survives a lost race is agi-out's failure arm, not this row)
mkh 29;mkdir -p $D/shimC;printf '#!/bin/sh\nif [ "$1" = commit-tree ]&&[ -e %s/racecommit ];then rm -f %s/racecommit;t=$(/usr/bin/git -C %s/t rev-parse refs/heads/posts/post1);n=$(/usr/bin/git -C %s/t commit-tree -m racer -p $t $t^{tree});/usr/bin/git -C %s/t update-ref refs/heads/posts/post1 $n;fi\nexec /usr/bin/git "$@"\n' $D $D $H $H $H >$D/shimC/git;chmod +x $D/shimC/git;: >$D/racecommit;g0=$(git -C $H/t rev-parse posts/post1:$GEO/ring);PS0=$PATH;PATH=$D/shimC:$PATH;CAP=capsule;out;rc=$?;PATH=$PS0
ok "ra1-a-raced-ring-commit-misses-the-cas a racer moves posts/post1 inside agi-at: agi-out rc=$rc (want 75), the branch tip is the racer's [$(git -C $H/t log -1 --format=%s posts/post1)] (want racer), commits $(nc) (want 2: genesis + the racer), the branch's ring is still the genesis ring: $([ "$(git -C $H/t rev-parse posts/post1:$GEO/ring)" = "$g0" ]&&echo yes||echo NO) (want yes: our ring commit did not land)" '[ "$rc" = 75 ]&&[ "$(git -C $H/t log -1 --format=%s posts/post1)" = racer ]&&[ "$(nc)" = 2 ]&&[ "$(git -C $H/t rev-parse posts/post1:$GEO/ring)" = "$g0" ]'
echo "agi-out-states: $f FAIL";exit $f
