#!/usr/bin/env python3
"""Reproduce the stale-.pyc race described in hypothesis:a01-390e52ad-e286a2.

Protocol (from the hypothesis):
  One process rewrites a module under test while a second process imports
  and runs pytest against it in a loop, with default bytecode caching.
  Confirm intermittent stale results.

  Then repeat with -B/PYTHONDONTWRITEBYTECODE=1 and confirm the race no
  longer reproduces across N=20 repeated trials (zero flips).

We use a tiny 'sensor' module that exports a monotonically-increasing version
counter. The writer rewrites it; the reader imports it and checks that the
imported version matches what it told the writer to write. A mismatch means
stale bytecode was served despite the source file being newer.

We run N=20 trials in each regime.
"""

import importlib
import importlib.util
import os
import random
import subprocess
import sys
import tempfile
import threading
import time
from pathlib import Path

SENSOR_CODE_TPL = """\
# sensor module — generated by _race_repro.py
VERSION = {version}
"""


def make_sensor_py(sensor_dir: Path, version: int) -> Path:
    path = sensor_dir / "sensor.py"
    # Atomic write: write to temp, rename
    tmp = path.with_suffix(".py.tmp")
    tmp.write_text(SENSOR_CODE_TPL.format(version=version))
    tmp.rename(path)
    return path


def writer_thread(sensor_dir: Path, stop_event: threading.Event, max_version: int = 500):
    """Repeatedly rewrite sensor.py with increasing versions."""
    version = 0
    while not stop_event.is_set() and version < max_version:
        version += 1
        # Every 5 writes, delay a tiny bit to give the reader a window
        make_sensor_py(sensor_dir, version)
        if version % 5 == 0:
            time.sleep(0.01)


def run_reader_trial(sensor_dir: Path, trial_num: int, no_bytecode: bool) -> dict:
    """One reader trial: import sensor module fresh, check version."""
    # Build a small runner script that imports sensor fresh
    runner_code = f"""\
import sys
sys.path.insert(0, {str(sensor_dir)!r})

# Clear any cached import of 'sensor'
if 'sensor' in sys.modules:
    del sys.modules['sensor']
if 'sensor' in sys.modules:
    del sys.modules['sensor']

import importlib.util
spec = importlib.util.spec_from_file_location("sensor", {str(sensor_dir / "sensor.py")!r})
mod = importlib.util.module_from_spec(spec)
sys.modules["sensor"] = mod
spec.loader.exec_module(mod)
# Must not come from stale .pyc
version = mod.VERSION
# Report version as a single integer on stdout
print(f"VERSION={{version}}")
"""
    runner_path = sensor_dir / f"_runner_{trial_num}.py"
    runner_path.write_text(runner_code)

    env = os.environ.copy()
    if no_bytecode:
        env["PYTHONDONTWRITEBYTECODE"] = "1"

    result = subprocess.run(
        [sys.executable, str(runner_path)],
        capture_output=True, text=True, timeout=10, env=env,
    )
    # Parse VERSION=N from output
    version = None
    for line in result.stdout.splitlines():
        line = line.strip()
        if line.startswith("VERSION="):
            try:
                version = int(line.split("=", 1)[1])
            except ValueError:
                pass
    rc = result.returncode
    stderr = result.stderr.strip()

    runner_path.unlink(missing_ok=True)
    return {"version": version, "rc": rc, "stderr": stderr, "trial": trial_num}


def run_trials(n_trials: int, no_bytecode: bool, sensor_dir: Path, writer_delay: float = 0.005) -> list:
    """Run N reader trials while a writer rewrites sensor.py.

    Returns a list of trial results.
    """
    stop = threading.Event()
    results = []

    # Prime the sensor file
    make_sensor_py(sensor_dir, 0)

    # Start writer in background
    wt = threading.Thread(target=writer_thread, args=(sensor_dir, stop), daemon=True)
    wt.start()

    # Give writer a head start
    time.sleep(writer_delay * 2)

    for i in range(n_trials):
        r = run_reader_trial(sensor_dir, i, no_bytecode)
        results.append(r)
        # Small delay between trials to overlap with writer
        time.sleep(writer_delay)

    stop.set()
    wt.join(timeout=5)
    return results


def count_mismatches(results: list) -> int:
    """Count trials where the imported version is NOT the maximum version
    written so far.  A version < the max written means stale bytecode."""
    if not results:
        return 0
    max_version_written = max(r["version"] for r in results if r["version"] is not None)
    mismatches = 0
    for r in results:
        v = r["version"]
        max_possible = max_version_written  # simplified
        if v is None:
            mismatches += 1
            r["reason"] = "no_version_parsed"
        elif v < max_possible:
            mismatches += 1
            r["reason"] = f"stale(v={v}, max={max_possible})"
    return mismatches


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--trials", type=int, default=20,
                        help="Number of reader trials per regime (default: 20)")
    parser.add_argument("--writer-delay", type=float, default=0.002,
                        help="Delay between reader trials (default: 0.002)")
    args = parser.parse_args()

    with tempfile.TemporaryDirectory(prefix="race_repro_") as tmpdir:
        sensor_dir = Path(tmpdir)
        print(f"Sensor dir: {sensor_dir}")

        # --- Regime 1: with bytecode caching (no -B) ---
        print(f"\n{'='*60}")
        print(f"REGIME 1: DEFAULT (bytecode caching ON)")
        print(f"  {args.trials} trials, writer delay={args.writer_delay}")
        print(f"{'='*60}")
        results_normal = run_trials(args.trials, no_bytecode=False,
                                    sensor_dir=sensor_dir, writer_delay=args.writer_delay)
        mismatches_normal = count_mismatches(results_normal)
        for r in results_normal:
            if r.get("reason"):
                print(f"  Trial {r['trial']}: version={r['version']} — {r['reason']}")
            else:
                print(f"  Trial {r['trial']}: version={r['version']} OK")
        print(f"\n  Mismatches: {mismatches_normal}/{args.trials}")

        # Clean cached .pyc files before next regime
        import shutil
        for pycache in sensor_dir.glob("**/__pycache__"):
            shutil.rmtree(pycache, ignore_errors=True)

        # --- Regime 2: with PYTHONDONTWRITEBYTECODE=1 ---
        print(f"\n{'='*60}")
        print(f"REGIME 2: PYTHONDONTWRITEBYTECODE=1 (bytecode cache OFF)")
        print(f"  {args.trials} trials, writer delay={args.writer_delay}")
        print(f"{'='*60}")
        results_nobc = run_trials(args.trials, no_bytecode=True,
                                  sensor_dir=sensor_dir, writer_delay=args.writer_delay)
        mismatches_nobc = count_mismatches(results_nobc)
        for r in results_nobc:
            if r.get("reason"):
                print(f"  Trial {r['trial']}: version={r['version']} — {r['reason']}")
            else:
                print(f"  Trial {r['trial']}: version={r['version']} OK")
        print(f"\n  Mismatches: {mismatches_nobc}/{args.trials}")

        # Summary
        print(f"\n{'='*60}")
        print("SUMMARY")
        print(f"{'='*60}")
        print(f"  Regime 1 (default):     {mismatches_normal}/{args.trials} mismatches")
        print(f"  Regime 2 (no bytecode): {mismatches_nobc}/{args.trials} mismatches")

        if mismatches_normal > 0:
            print("\n  ✓ Race reproduced with default bytecode caching.")
        else:
            print("\n  ✗ Race NOT reproduced with default bytecode caching.")
            print("    (Likely depends on filesystem timing or Python version.)")

        if mismatches_nobc == 0:
            print("  ✓ Zero mismatches with PYTHONDONTWRITEBYTECODE=1 — consistent with hypothesis.")
        else:
            print(f"  ✗ {mismatches_nobc} mismatches still with -B — race is NOT .pyc-driven.")

        verdict = "proved" if mismatches_normal > 0 and mismatches_nobc == 0 else "disproved" if mismatches_normal > 0 and mismatches_nobc > 0 else "inconclusive"
        print(f"\n  Verdict: {verdict}")
        return 0 if mismatches_normal > 0 else 1


if __name__ == "__main__":
    sys.exit(main())