#!/usr/bin/env python3
"""Precise stale-.pyc race reproducer for hypothesis:a01-390e52ad-e286a2.

Protocol (from the hypothesis):
  One process rewrites a module under test while a second process imports
  it in a loop, with default bytecode caching. Confirm intermittent stale
  results: reader gets an OLD version despite the source file having been
  UPDATED before the import.

  Then repeat with -B/PYTHONDONTWRITEBYTECODE=1 and confirm the race no
  longer reproduces across N=20 repeated trials (zero flips).

KEY FIX over v1: we track exactly which version was written IMMEDIATELY
before each reader trial, then check whether the reader got THAT version
or an older one.  This distinguishes genuine stale-.pyc from the trivial
case where the writer kept writing after the trial started.
"""

import os
import shutil
import subprocess
import sys
import threading
import time
from pathlib import Path

SENSOR_CODE_TPL = """\
# sensor module — generated by _race_repro_v2.py
VERSION = {version}
"""


def atomic_write(path: Path, content: str):
    """Write content to path atomically (write temp, rename)."""
    tmp = path.with_suffix(".py.tmp")
    tmp.write_text(content)
    tmp.rename(path)  # atomic on same filesystem (Linux ext4, etc.)


# ── Shared state ──────────────────────────────────────────────
# The writer sets (version, event) so the reader knows which
# version was current when the writer signalled "go".


class WriterState:
    def __init__(self, sensor_dir: Path):
        self.sensor_path = sensor_dir / "sensor.py"
        self.version = 0
        self.ready = threading.Event()
        self.ready.clear()
        self._stop = threading.Event()

    def stop(self):
        self._stop.set()
        self.ready.set()  # unblock any waiting reader

    @property
    def stopped(self):
        return self._stop.is_set()


def writer_loop(state: WriterState):
    """Write a fresh sensor.py, then signal ready.  Wait for reader
    to acknowledge before writing the next version."""
    while not state.stopped:
        state.version += 1
        atomic_write(state.sensor_path,
                     SENSOR_CODE_TPL.format(version=state.version))
        state.ready.set()  # signal reader: version N is written
        # Busy-wait until reader has imported (or stop)
        while state.ready.is_set() and not state.stopped:
            time.sleep(0.0001)


def run_reader_trial(state: WriterState, trial_num: int,
                     no_bytecode: bool, sensor_dir: Path) -> dict:
    """Wait for writer to signal a version, then import sensor and check."""

    # Wait for writer to set ready
    for _ in range(5000):  # 5000 * 100µs = 0.5s timeout
        if state.ready.is_set():
            break
        time.sleep(0.0001)
    if not state.ready.is_set():
        return {"trial": trial_num, "error": "writer_timeout",
                "expected": state.version, "got": None}

    # Snapshot what the writer claims is current
    expected_version = state.version

    # Now import sensor in a subprocess
    runner_code = """
import sys, importlib, importlib.util
from pathlib import Path
sensor_dir = {sensor_dir!r}
sensor_py = {sensor_py!r}
for key in list(sys.modules.keys()):
    if 'sensor' in key:
        del sys.modules[key]
import shutil
for p in Path(sensor_dir).rglob('__pycache__'):
    shutil.rmtree(p, ignore_errors=True)
spec = importlib.util.spec_from_file_location('sensor', sensor_py)
m = importlib.util.module_from_spec(spec)
sys.modules['sensor'] = m
spec.loader.exec_module(m)
print('VERSION=' + str(m.VERSION), flush=True)
""".format(sensor_dir=str(sensor_dir), sensor_py=str(state.sensor_path))

    runner_path = sensor_dir / f"_runner_{trial_num}.py"
    runner_path.write_text(runner_code)

    env = os.environ.copy()
    if no_bytecode:
        env["PYTHONDONTWRITEBYTECODE"] = "1"

    result = subprocess.run(
        [sys.executable, str(runner_path)],
        capture_output=True, text=True, timeout=10, env=env,
    )
    runner_path.unlink(missing_ok=True)

    # Parse VERSION=N
    got_version = None
    for line in result.stdout.splitlines():
        line = line.strip()
        if line.startswith("VERSION="):
            try:
                got_version = int(line.split("=", 1)[1])
            except ValueError:
                pass

    # Signal writer: reader is done, proceed
    state.ready.clear()

    return {
        "trial": trial_num,
        "expected": expected_version,
        "got": got_version,
        "rc": result.returncode,
        "stderr": result.stderr.strip(),
    }


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--trials", type=int, default=20)
    args = parser.parse_args()

    sensor_dir = Path(tempfile.mkdtemp(prefix="race_repro_v2_"))
    print(f"Sensor dir: {sensor_dir}")

    # Prime sensor.py at version 0
    atomic_write(sensor_dir / "sensor.py", SENSOR_CODE_TPL.format(version=0))

    def run_regime(no_bytecode: bool, label: str):
        state = WriterState(sensor_dir)
        writer = threading.Thread(target=writer_loop, args=(state,), daemon=True)
        writer.start()

        results = []
        for i in range(args.trials):
            r = run_reader_trial(state, i, no_bytecode, sensor_dir)
            results.append(r)
            # Brief inter-trial delay so writer has time to increment
            time.sleep(0.002)

        state.stop()
        writer.join(timeout=5)

        print(f"\n{label}")
        print(f"{'─' * len(label)}")
        stale_count = 0
        error_count = 0
        for r in results:
            exp, got = r.get("expected"), r.get("got")
            if r.get("error"):
                print(f"  Trial {r['trial']}: ERROR {r['error']}")
                error_count += 1
            elif got is None:
                print(f"  Trial {r['trial']}: expected={exp}, got=None (parse failure)")
                error_count += 1
            elif got < exp:
                stale_count += 1
                age = exp - got
                print(f"  Trial {r['trial']}: expected={exp}, got={got} — STALE (-{age})")
            elif got == exp:
                print(f"  Trial {r['trial']}: expected={exp}, got={got} OK")
            elif got > exp:
                # Writer incremented during our subprocess — technically fine
                print(f"  Trial {r['trial']}: expected={exp}, got={got} (ahead — OK)")
        print(f"\n  Stale imports: {stale_count}/{args.trials}")
        print(f"  Errors:        {error_count}/{args.trials}")
        return stale_count, error_count

    # Regime 1 — default bytecode caching
    s1, e1 = run_regime(no_bytecode=False, label="REGIME 1: Default bytecode caching (no -B)")

    # Wipe __pycache__ between regimes
    for p in Path(sensor_dir).rglob("__pycache__"):
        shutil.rmtree(p, ignore_errors=True)

    # Regime 2 — PYTHONDONTWRITEBYTECODE=1
    s2, e2 = run_regime(no_bytecode=True, label="REGIME 2: PYTHONDONTWRITEBYTECODE=1 (no cache)")

    # Summary
    print(f"\n{'=' * 50}")
    print("SUMMARY")
    print(f"{'=' * 50}")
    print(f"  Default (with cache): {s1}/{args.trials} stale imports ({s1*100//args.trials}%)")
    print(f"  -B (no cache):        {s2}/{args.trials} stale imports ({s2*100//args.trials}%)")

    if s1 > 0 and s2 == 0:
        print("\n  ✓ HYPOTHESIS PROVED: stale .pyc causes the race, -B eliminates it.")
    elif s1 > 0 and s2 > 0:
        print("\n  ✗ HYPOTHESIS DISPROVED: race still reproduces with -B — not .pyc-driven.")
    elif s1 == 0:
        print("\n  ∘ INCONCLUSIVE: could not reproduce the race (may need tighter timing).")
    else:
        print(f"\n  ∘ INCONCLUSIVE: unhandled case (s1={s1}, s2={s2})")

    return 0


if __name__ == "__main__":
    import tempfile
    main()